image: python:3.10

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - py -m unittest discover -s "./tests" -p "test_*.py"
